# Generated by Django 3.2.19 on 2026-08-04 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_auto_20260802_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_certification',
            field=models.CharField(choices=[('U', 'U - Unrestricted Public Exhibition'), ('U/A 7+', 'U/A 7+ - Parental Guidance for under 7'), ('U/A 13+', 'U/A 13+ - Parental Guidance for under 13'), ('U/A 16+', 'U/A 16+ - Parental Guidance for under 16'), ('A', 'A - Restricted to Adults'), ('S', 'S - Restricted to Special Class')], default='U/A 13+', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration_mins',
            field=models.PositiveIntegerField(default=120, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube Trailer URL (e.g. https://www.youtube.com/watch?v=...)', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.CreateModel(
            name='MoviePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movie_posters/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=10, help_text='Rating from 1 to 10')),
                ('comment', models.TextField()),
                ('is_verified_viewer', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
                ('report_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
