# Generated by Django 3.2.19 on 2026-08-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20260815_2006'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'booked_at'], name='movies_book_status_40a788_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['show_date', 'status'], name='movies_book_show_da_c82640_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['movie', 'status'], name='movies_book_movie_i_cb8d13_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['theater', 'status'], name='movies_book_theater_e79b80_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='movies_book_user_id_9b70b3_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genre', 'rating'], name='movies_movi_genre_772261_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['language', 'rating'], name='movies_movi_languag_431ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'),
        ),
        migrations.AddIndex(
            model_name='movieview',
            index=models.Index(fields=['user', 'viewed_at'], name='movies_movi_user_id_3d3b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='movieview',
            index=models.Index(fields=['session_key', 'viewed_at'], name='movies_movi_session_b69541_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='movies_paym_status_8acdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_order_id'], name='movies_paym_razorpa_39457f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking_group_id'], name='movies_paym_booking_2b546e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['movie', 'is_reported'], name='movies_revi_movie_i_3a5752_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_verified_viewer'], name='movies_revi_is_veri_8645be_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['theater', 'is_booked'], name='movies_seat_theater_7e5f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['reserved_at', 'reserved_by'], name='movies_seat_reserve_e65b87_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['city', 'time'], name='movies_thea_city_3d4d26_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['movie', 'city'], name='movies_thea_movie_i_79c43a_idx'),
        ),
    ]
