# Generated by Django 3.2.19 on 2026-08-15 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0008_auto_20260815_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('events', 'Live Events'), ('plays', 'Plays & Theater'), ('sports', 'Sports Matches'), ('music', 'Music & Concerts')], default='events', max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('banner_url', models.URLField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(choices=[('mumbai', 'Mumbai'), ('delhi', 'Delhi'), ('bangalore', 'Bangalore'), ('chennai', 'Chennai'), ('hyderabad', 'Hyderabad'), ('kolkata', 'Kolkata'), ('pune', 'Pune'), ('ahmedabad', 'Ahmedabad'), ('jaipur', 'Jaipur'), ('surat', 'Surat')], default='mumbai', max_length=50)),
                ('venue_name', models.CharField(default='Main Arena / Auditorium', max_length=255)),
                ('event_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=499.0, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('organizer', models.CharField(default='BookMySeat Live', max_length=255)),
                ('duration_mins', models.PositiveIntegerField(default=150)),
                ('language', models.CharField(default='English / Hindi', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_count', models.PositiveIntegerField(default=1)),
                ('booking_id', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed Payment')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'city'], name='movies_even_categor_a07883_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date'], name='movies_even_event_d_1f486d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventbooking',
            index=models.Index(fields=['user', 'status'], name='movies_even_user_id_4fffd0_idx'),
        ),
        migrations.AddIndex(
            model_name='eventbooking',
            index=models.Index(fields=['event', 'status'], name='movies_even_event_i_6ac498_idx'),
        ),
    ]
