# Generated by Django 3.2.19 on 2026-08-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20260819_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(choices=[('mumbai', 'Mumbai'), ('delhi', 'Delhi-NCR'), ('bangalore', 'Bengaluru / Bangalore'), ('chennai', 'Chennai'), ('hyderabad', 'Hyderabad'), ('kolkata', 'Kolkata'), ('pune', 'Pune'), ('ahmedabad', 'Ahmedabad'), ('jalandhar', 'Jalandhar'), ('amritsar', 'Amritsar'), ('ludhiana', 'Ludhiana'), ('chandigarh', 'Chandigarh'), ('patiala', 'Patiala'), ('bathinda', 'Bathinda'), ('jaipur', 'Jaipur'), ('surat', 'Surat'), ('lucknow', 'Lucknow'), ('kanpur', 'Kanpur'), ('nagpur', 'Nagpur'), ('indore', 'Indore'), ('thane', 'Thane'), ('bhopal', 'Bhopal'), ('visakhapatnam', 'Visakhapatnam'), ('patna', 'Patna'), ('vadodara', 'Vadodara'), ('ghaziabad', 'Ghaziabad'), ('agra', 'Agra'), ('nashik', 'Nashik'), ('faridabad', 'Faridabad'), ('meerut', 'Meerut'), ('rajkot', 'Rajkot'), ('varanasi', 'Varanasi'), ('srinagar', 'Srinagar'), ('aurangabad', 'Chhatrapati Sambhajinagar / Aurangabad'), ('dhanbad', 'Dhanbad'), ('navi_mumbai', 'Navi Mumbai'), ('allahabad', 'Prayagraj / Allahabad'), ('ranchi', 'Ranchi'), ('howrah', 'Howrah'), ('coimbatore', 'Coimbatore'), ('jabalpur', 'Jabalpur'), ('gwalior', 'Gwalior'), ('vijayawada', 'Vijayawada'), ('jodhpur', 'Jodhpur'), ('madurai', 'Madurai'), ('raipur', 'Raipur'), ('kota', 'Kota'), ('guwahati', 'Guwahati'), ('solapur', 'Solapur'), ('bareilly', 'Bareilly'), ('moradabad', 'Moradabad'), ('mysore', 'Mysuru / Mysore'), ('gurgaon', 'Gurugram / Gurgaon'), ('noida', 'Noida'), ('mangalore', 'Mangaluru / Mangalore'), ('kochi', 'Kochi / Cochin'), ('goa', 'Goa'), ('trivandrum', 'Thiruvananthapuram / Trivandrum'), ('pondicherry', 'Puducherry / Pondicherry'), ('dehradun', 'Dehradun'), ('shimla', 'Shimla'), ('bhubaneswar', 'Bhubaneswar'), ('cuttack', 'Cuttack'), ('jammu', 'Jammu')], default='mumbai', max_length=50),
        ),
        migrations.AlterField(
            model_name='theater',
            name='city',
            field=models.CharField(choices=[('mumbai', 'Mumbai'), ('delhi', 'Delhi-NCR'), ('bangalore', 'Bengaluru / Bangalore'), ('chennai', 'Chennai'), ('hyderabad', 'Hyderabad'), ('kolkata', 'Kolkata'), ('pune', 'Pune'), ('ahmedabad', 'Ahmedabad'), ('jalandhar', 'Jalandhar'), ('amritsar', 'Amritsar'), ('ludhiana', 'Ludhiana'), ('chandigarh', 'Chandigarh'), ('patiala', 'Patiala'), ('bathinda', 'Bathinda'), ('jaipur', 'Jaipur'), ('surat', 'Surat'), ('lucknow', 'Lucknow'), ('kanpur', 'Kanpur'), ('nagpur', 'Nagpur'), ('indore', 'Indore'), ('thane', 'Thane'), ('bhopal', 'Bhopal'), ('visakhapatnam', 'Visakhapatnam'), ('patna', 'Patna'), ('vadodara', 'Vadodara'), ('ghaziabad', 'Ghaziabad'), ('agra', 'Agra'), ('nashik', 'Nashik'), ('faridabad', 'Faridabad'), ('meerut', 'Meerut'), ('rajkot', 'Rajkot'), ('varanasi', 'Varanasi'), ('srinagar', 'Srinagar'), ('aurangabad', 'Chhatrapati Sambhajinagar / Aurangabad'), ('dhanbad', 'Dhanbad'), ('navi_mumbai', 'Navi Mumbai'), ('allahabad', 'Prayagraj / Allahabad'), ('ranchi', 'Ranchi'), ('howrah', 'Howrah'), ('coimbatore', 'Coimbatore'), ('jabalpur', 'Jabalpur'), ('gwalior', 'Gwalior'), ('vijayawada', 'Vijayawada'), ('jodhpur', 'Jodhpur'), ('madurai', 'Madurai'), ('raipur', 'Raipur'), ('kota', 'Kota'), ('guwahati', 'Guwahati'), ('solapur', 'Solapur'), ('bareilly', 'Bareilly'), ('moradabad', 'Moradabad'), ('mysore', 'Mysuru / Mysore'), ('gurgaon', 'Gurugram / Gurgaon'), ('noida', 'Noida'), ('mangalore', 'Mangaluru / Mangalore'), ('kochi', 'Kochi / Cochin'), ('goa', 'Goa'), ('trivandrum', 'Thiruvananthapuram / Trivandrum'), ('pondicherry', 'Puducherry / Pondicherry'), ('dehradun', 'Dehradun'), ('shimla', 'Shimla'), ('bhubaneswar', 'Bhubaneswar'), ('cuttack', 'Cuttack'), ('jammu', 'Jammu')], default='mumbai', max_length=50),
        ),
    ]
