# Generated by Django 3.2.19 on 2026-08-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20260819_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_url',
            field=models.URLField(blank=True, help_text='TMDB HD Backdrop Banner URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, help_text='TMDB HD Poster Image URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, help_text='TMDB Movie ID', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movieposter',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, default='Various Artistes'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('kannada', 'Kannada'), ('malayalam', 'Malayalam'), ('punjabi', 'Punjabi'), ('bengali', 'Bengali'), ('marathi', 'Marathi')], default='hindi', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube Trailer URL', null=True),
        ),
        migrations.AlterField(
            model_name='movieposter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_posters/'),
        ),
    ]
