# Generated by Django 3.2.19 on 2026-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20260819_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='backdrop_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='last_synced_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
        migrations.RemoveField(
            model_name='movieposter',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('kannada', 'Kannada'), ('malayalam', 'Malayalam'), ('bengali', 'Bengali'), ('marathi', 'Marathi')], default='hindi', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube Trailer URL (e.g. https://www.youtube.com/watch?v=...)', null=True),
        ),
    ]
